version: '3'

services:
  backend:
    build:
      context: ./CompetenceProject-Backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database/competenceproject?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - '8080:8080'
    depends_on:
      - database
  database:
    container_name: 'mysqldb'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: competenceproject
    expose:
      - '3307'
    ports:
      - '3307:3307'
    restart: always

